# Generated by Django 3.1.4 on 2020-12-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startImg', models.ImageField(height_field=1300, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для стартовой страницы', width_field=1920)),
                ('skillImg', models.ImageField(height_field=1040, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для раздела навыков', width_field=800)),
                ('contactImg', models.ImageField(height_field=1300, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для формы обратной связи', width_field=1920)),
            ],
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-year'], 'verbose_name': 'Работа(у)', 'verbose_name_plural': 'Места работы'},
        ),
    ]
