# Generated by Django 3.1.4 on 2020-12-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0002_auto_20201227_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название соц сети (иконки)')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на соц сеть')),
            ],
            options={
                'verbose_name': 'Ссылка на соц сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.AlterModelOptions(
            name='allimg',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Все изображения'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='allimg',
            name='contactImg',
            field=models.ImageField(help_text='Размер изображения должен быть 1920х1300', upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для формы обратной связи'),
        ),
        migrations.AlterField(
            model_name='allimg',
            name='skillImg',
            field=models.ImageField(help_text='Размер изображения должен быть 800х1040', upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для раздела навыков'),
        ),
        migrations.AlterField(
            model_name='allimg',
            name='startImg',
            field=models.ImageField(help_text='Размер изображения должен быть 1920х1300', upload_to='photos/%Y/%m/%d/', verbose_name='Картинка для стартовой страницы'),
        ),
    ]
