# Generated by Django 3.1.4 on 2020-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0005_work_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата окончания разработки'),
        ),
    ]
